from typing import Dict, Any
from collectors.base_collector import BaseCollector


# ---------------------------------------------------------------------------
# COSTANTI — Mapping penalità Google
# ---------------------------------------------------------------------------
PENALTY_MAPPING = {
    "internal": "P-INT",
    "external": "P-EXT",
    "autogenerated": "P-AUT",
    "low_quality": "P-LOW"
}


class ManualCollector(BaseCollector):
    """Raccoglie dati manuali/semi-automatici."""
    
    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
    
    def is_available(self) -> bool:
        """Il collector manuale è sempre disponibile."""
        return True
    
    def collect(self, domain: str) -> Dict[str, Any]:
        """Esegue check manuali per il dominio."""
        self.logger.info(f"🔍 Esecuzione check manuali per {domain}...")
        
        # Verifica HTTPS
        https_present = domain.startswith('https://')
        
        # Penalty check (placeholder - richiederebbe GSC access)
        penalties = self._check_penalties()
        
        return {
            'https_present': https_present,
            'penalties': penalties
        }
    
    def _check_penalties(self) -> Dict[str, bool]:
        """Verifica penalità Google (placeholder)."""
        return {
            'internal': False,
            'external': False,
            'autogenerated': False,
            'low_quality': False
        }