import requests
from typing import Dict, Any
from collectors.base_collector import BaseCollector

class ManualCollector(BaseCollector):
    """Raccoglie dati che richiedono verifica manuale o semi-automatica."""

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)
    
    def is_available(self) -> bool:
        """Il collector manuale è sempre disponibile."""
        return True
    
    def collect(self, domain: str) -> Dict[str, Any]:
        self.logger.info(f"🔍 Esecuzione check manuali per {domain}...")
        
        # Normalizza il dominio
        clean_domain = domain.replace('https://', '').replace('http://', '').split('/')[0]
        
        # 1. Verifica HTTPS automaticamente
        https_present = self._check_https(clean_domain)
        
        # 2. Altri check manuali (da compilare manualmente o da file CSV)
        return {
            "penalties": {
                "internal": False,      # False = nessun problema (default)
                "external": False,
                "autogenerated": False,
                "low_quality": False,
            },
            "hreflang": None,          # None = da verificare
            "content_language": None,
            "https_present": https_present,
            "domain_age_days": None,
        }
    
    def _check_https(self, domain: str) -> bool:
        """Verifica se HTTPS è attivo sul dominio."""
        try:
            # Prova prima con https
            response = requests.get(f"https://{domain}", timeout=10, allow_redirects=True)
            if response.status_code == 200:
                return True
            
            # Se fallisce, prova con www
            response = requests.get(f"https://www.{domain}", timeout=10, allow_redirects=True)
            return response.status_code == 200
            
        except requests.exceptions.SSLError:
            return False
        except requests.exceptions.ConnectionError:
            return False
        except Exception as e:
            self.logger.warning(f"Errore verifica HTTPS: {e}")
            return False